### ISSUE TITLE
没有默认的管理员账号吗？

### ISSUE THREAD

**Issue by ngugc** [greyu/cms_community_e_commerce#1]
也没办法注册用户，要自己填数据库吗？

**Comment by greyu** [comment]
因为这个项目我是前后端一起写的，就没有再去做模拟数据。
这个项目的服务端代码在： https://github.com/greyu/backend_cloud_commodity。你有兴趣可以自己尝试跑一下。
我这边，这周比较忙，目前打算下周再把服务端部署到服务器上。

**Comment by ngugc** [comment]
谢谢！服务端我是跑起来的，但数据库没有账户数据，还是没办法登陆体验。
如果能在数据库脚本里简单搞个管理员账号，方便大家初次体验，可能会更多人感兴趣。

**Comment by greyu** [comment]
好的，谢谢提醒。我去弄一些测试数据

**Comment by greyu** [comment]
服务端代码更新了
1. 添加了几个管理员和用户的测试样例，sql代码在：https://github.com/greyu/backend_cloud_commodity/blob/master/src/main/resources/sql/cloud_commodity.sql。
2. 商品和分类之类的还是要自己添加，因为要添加图片
